export enum LoginFailureReason {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_VERIFIED = 'NOT_VERIFIED',
  BLOCKED = 'BLOCKED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}

export enum RefreshTokensFailureReason {
  INVALID_JWT_PAYLOAD = 'INVALID_JWT_PAYLOAD',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_VERIFIED = 'NOT_VERIFIED',
  BLOCKED = 'BLOCKED',
}

export enum ResetPasswordFailureReason {
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  TOKEN_INVALID_OR_EXPIRED = 'TOKEN_INVALID_OR_EXPIRED',
}

export enum ChangePasswordFailureReason {
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  PASSWORD_NOT_CONFIGURED = 'PASSWORD_NOT_CONFIGURED',
  CURRENT_PASSWORD_INVALID = 'CURRENT_PASSWORD_INVALID',
}
