export enum TechnologyCategory {
  LANGUAGE = 'LANGUAGE',
  FRAMEWORK = 'FRAMEWORK',
  LIBRARY = 'LIBRARY',
  DATABASE = 'DATABASE',
  STORAGE = 'STORAGE',
  INFRA = 'INFRA',
  PROTOCOL = 'PROTOCOL',
  ARCHITECTURE = 'ARCHITECTURE',
  AUTH = 'AUTH',
  TESTING = 'TESTING',
  TOOL = 'TOOL',
  OTHER = 'OTHER',
}
